name: newsapp
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  http: ^0.12.1
  cached_network_image: ^2.2.0+1
  webview_flutter: ^0.3.22+1
  shimmer: ^1.1.1
  bloc: ^6.0.1
  equatable: ^1.2.3
  flutter_bloc: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  uses-material-design: true
